# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Decancer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Firebase/Auth'
pod 'GoogleSignIn'
pod ‘Firebase/Storage’
pod ‘SDWebImageSwiftUI’


  # Pods for Decancer

  target 'DecancerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DecancerUITests' do
    # Pods for testing
  end

end
